image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: notify
  - port: 35900
    onOpen: ignore

tasks:
  - before: nvm install 12 && nvm alias default 12
  - init: yarn install
  - command: yarn dev
