name: Lint

on: [push, pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
      - name: yarn lint
